local opt = { noremap = true, silent = true }
vim.keymap.set("n", "k", [[v:count ? 'k' : 'gk']], { noremap = true, expr = true })
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>-", "<C-W>s")
vim.keymap.set("n", "<leader>x", "<C-W>q")
vim.keymap.set("n", "<leader>\\", "<C-W>v")
vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<leader>h", "<C-W>h")
vim.keymap.set("n", "<leader>l", "<C-W>l")
vim.keymap.set("n", "<leader>k", "<C-W>k")
vim.keymap.set("n", "<leader>j", "<C-W>j")
vim.keymap.set("n", "j", [[v:count ? 'j' : 'gj']], { noremap = true, expr = true })
vim.keymap.set("n", "<leader>[", "<C-o>", opt)
vim.keymap.set("n", "<leader>]", "<C-i>", opt)
vim.keymap.set("n", "<leader>s", ":w<CR>", opt)
vim.keymap.set("n", "<leader>qq", ":wq<CR>", opt)
vim.keymap.set("n", "<leader>gun", ":q!<CR>", opt)
vim.keymap.set("n", "<C-z>", ":u<CR>", opt)
vim.keymap.set("n", "<leader>nh", ":nohlsearch<CR>", opt)
vim.keymap.set("n", "J", "5j", opt)
vim.keymap.set("n", "H", "5h", opt)
vim.keymap.set("n", "L", "5l", opt)
vim.keymap.set("n", "K", "5k", opt)
vim.keymap.set("n", "<leader>p", ":Files<CR>")
vim.keymap.set("n", "<leader>b", ":Buffers<CR>")
